/**
 * This file is auto-generated by generateVersionNumber.pl,
 * which is run automatically by the build script for a
 * project.
 * 
 * @author Mark Hawley
 */
package com.atmospherebbdo.util
{
	/**
	 * Returns the build version. Generated file.
	 * 
	 * @return String
	 */
	public function getBuildVersion() :String
	{
		return "05/21/2009 12:11 PM";
	}
}

